// 내 챌린지 저축 현황 액션 타입
export const GET_SAVING_INFO_PENDING = "GET_SAVING_INFO_PENDING";
export const GET_SAVING_INFO_SUCCESS = "GET_SAVING_INFO_SUCCESS";
export const GET_SAVING_INFO_FAIL = "GET_SAVING_INFO_FAIL";

// 챌린지 요약 정보 액션 타입
export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_ERROR = "GET_POSTS_ERROR";

// 내 챌린지 계좌 현황 보기
export const GET_SAVING_ACCOUNT_PENDING = "GET_SAVING_ACCOUNT_PENDING";
export const GET_SAVING_ACCOUNT_SUCCESS = "GET_SAVING_ACCOUNT_SUCCESS";
export const GET_SAVING_ACCOUNT_FAIL = "GET_SAVING_ACCOUNT_FAIL";
