// 내 챌린지 저축 현황 액션 타입
export const GET_SAVING_INFO_PENDING = "GET_SAVING_INFO_PENDING";
export const GET_SAVING_INFO_SUCCESS = "GET_SAVING_INFO_SUCCESS";
export const GET_SAVING_INFO_FAIL = "GET_SAVING_INFO_FAIL";

export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_ERROR = "GET_POSTS_ERROR";
